### ISSUE TITLE
Is this library usable?

### ISSUE THREAD

**Issue by playXE** [bnjbvr/minira#16]
I would like to use minira for my register-based bytecode, is it possible to use this library in this way?

**Comment by bnjbvr** [comment]
In theory, yes: we plan to use this in [Cranelift](https://github.com/CraneStation/cranelift), the idea was to make it modular so it can be reused in other crates as well. Note this is very work-in-progress-y, so there might be rough edges, and we offer no guarantee in API stability at this time: you should expect things to change, including the very name of this crate. There is not much documentation except for the doc comments in the interface.rs and the docs/ folder, hopefully that's sufficient, otherwise we can improve it.

**Comment by playXE** [comment]
Well, I will try to use minira in my bytecode, if will not work as planned then I will implement some very simple regallor for bytecode. :) Thanks for the information.
